plugins {
    id 'java'
}

group = 'com.example'
version = '1.1.0'

repositories {
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
    mavenCentral()
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.2.build.124-stable'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    archiveBaseName = 'VanillaVehicles'
}
