package com.wave100.client;

import com.wave100.WaveMod;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.model.geom.builders.PartPose;
import net.minecraft.world.entity.Entity;

/**
 * Honda Wave 100 style underbone motorcycle - modular entity model.
 *
 * <p>AUTO-GENERATED by {@code tools/generate_model.py}. Do not edit by hand:
 * change the generator spec and re-run it (see README). The layout is
 * Blockbench-compatible vanilla entity geometry.</p>
 *
 * <p>Animated part groups:</p>
 * <ul>
 *   <li>{@code steering} - yaw with the handlebars (front fork + wheel + fender)</li>
 *   <li>{@code forkLower} - slides along the fork axis for suspension travel</li>
 *   <li>{@code frontWheel} / {@code rearWheel} - spin around the X axis</li>
 *   <li>{@code sideStand} - swings down when parked, folds away when ridden</li>
 *   <li>{@code headlightLens}, {@code beamInner}, {@code beamOuter}, {@code tailLens}
 *       - emissive overlay passes for lights</li>
 * </ul>
 */
public class WaveModel extends HierarchicalModel<Entity> {

    public static final ModelLayerLocation LAYER =
            new ModelLayerLocation(WaveMod.id("wave_motorcycle"), "main");

    private final ModelPart root;

    public final ModelPart body;
    public final ModelPart windscreen;
    public final ModelPart sideStand;
    public final ModelPart steering;
    public final ModelPart handlebar;
    public final ModelPart fork;
    public final ModelPart forkLower;
    public final ModelPart frontWheel;
    public final ModelPart rearWheel;
    public final ModelPart headlightLens;
    public final ModelPart tailLens;
    public final ModelPart beamInner;
    public final ModelPart beamOuter;

    public WaveModel(ModelPart root) {
        this.root = root;
        this.body = root.getChild("body");
        this.windscreen = this.body.getChild("windscreen");
        this.sideStand = this.body.getChild("side_stand");
        this.steering = root.getChild("steering");
        this.handlebar = this.steering.getChild("handlebar");
        this.fork = this.steering.getChild("fork");
        this.forkLower = this.fork.getChild("fork_lower");
        this.frontWheel = this.forkLower.getChild("front_wheel");
        this.rearWheel = root.getChild("rear_wheel");
        this.headlightLens = root.getChild("headlight_lens");
        this.tailLens = root.getChild("tail_lens");
        this.beamInner = root.getChild("beam_inner");
        this.beamOuter = root.getChild("beam_outer");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
            .texOffs(86, 68)
            .addBox(-1.5F, 12.5F, -5.4F, 3F, 2F, 1.6F)
            .texOffs(113, 46)
            .addBox(-1.2F, 7.2F, -5.2F, 2.4F, 5.6F, 1.3F)
            .texOffs(0, 35)
            .addBox(-3F, 10.6F, -3.8F, 6F, 2.6F, 6.8F)
            .texOffs(58, 46)
            .addBox(-2.6F, 12.9F, -3.4F, 5.2F, 0.8F, 5.6F)
            .texOffs(27, 35)
            .addBox(-3.1F, 8.6F, 2.2F, 0.9F, 1.4F, 8.4F)
            .texOffs(47, 35)
            .addBox(2.2F, 8.6F, 2.2F, 0.9F, 1.4F, 8.4F)
            .texOffs(20, 73)
            .addBox(-2.6F, 8.6F, 9.8F, 5.2F, 1.4F, 1.6F)
            .texOffs(76, 62)
            .addBox(-2.8F, 5.2F, 9.4F, 0.8F, 3.6F, 1F)
            .texOffs(81, 62)
            .addBox(2F, 5.2F, 9.4F, 0.8F, 3.6F, 1F)
            .texOffs(0, 23)
            .addBox(-3.2F, 5.2F, -3.4F, 6.4F, 3.6F, 6.6F)
            .texOffs(81, 46)
            .addBox(-4F, 5.6F, -2.2F, 0.8F, 2.6F, 4.2F)
            .texOffs(92, 46)
            .addBox(3.2F, 5.6F, -2.2F, 0.8F, 2.6F, 4.2F)
            .texOffs(103, 62)
            .addBox(-2.4F, 8.8F, -1.6F, 4.8F, 0.4F, 3.2F)
            .texOffs(0, 68)
            .addBox(-2.4F, 9.4F, -1.6F, 4.8F, 0.4F, 3.2F)
            .texOffs(17, 68)
            .addBox(-2.4F, 10F, -1.6F, 4.8F, 0.4F, 3.2F)
            .texOffs(83, 73)
            .addBox(-5.7F, 4.8F, 0.6F, 1.7F, 0.55F, 1.8F)
            .texOffs(91, 73)
            .addBox(4F, 4.8F, 0.6F, 1.7F, 0.55F, 1.8F)
            .texOffs(113, 78)
            .addBox(-4.3F, 4.7F, 0.7F, 1.3F, 0.8F, 1.2F)
            .texOffs(119, 78)
            .addBox(3F, 4.7F, 0.7F, 1.3F, 0.8F, 1.2F)
            .texOffs(85, 23)
            .addBox(-3.4F, 11.2F, 2.5F, 6.8F, 1.4F, 8.5F)
            .texOffs(22, 55)
            .addBox(-3.2F, 11.8F, 11F, 6.4F, 1.8F, 3.4F)
            .texOffs(86, 0)
            .addBox(-3.1F, 10.4F, 2.5F, 6.2F, 0.9F, 11.8F)
            .texOffs(47, 23)
            .addBox(-4.3F, 9F, 3.6F, 1.2F, 2.6F, 7.6F)
            .texOffs(66, 23)
            .addBox(3.1F, 9F, 3.6F, 1.2F, 2.6F, 7.6F)
            .texOffs(0, 55)
            .addBox(-3.3F, 10.6F, 14.4F, 6.6F, 2F, 3.8F)
            .texOffs(76, 55)
            .addBox(-2.7F, 12.6F, 14.8F, 5.4F, 0.8F, 3.4F)
            .texOffs(56, 78)
            .addBox(-2F, 11.1F, 18.2F, 4F, 1.2F, 0.5F)
            .texOffs(103, 35)
            .addBox(-2.9F, 9.4F, 7.6F, 5.8F, 1.1F, 6.2F)
            .texOffs(41, 78)
            .addBox(-2.9F, 10.4F, 7.3F, 5.8F, 0.5F, 1.2F)
            .texOffs(61, 73)
            .addBox(-2.2F, 8.9F, 18.1F, 4.4F, 2.2F, 0.35F)
            .texOffs(55, 55)
            .addBox(-3F, 13.6F, 15.2F, 6F, 0.5F, 3.6F)
            .texOffs(108, 68)
            .addBox(-2.8F, 12.6F, 15.4F, 0.6F, 1F, 2.8F)
            .texOffs(116, 68)
            .addBox(2.2F, 12.6F, 15.4F, 0.6F, 1F, 2.8F)
            .texOffs(35, 73)
            .addBox(-3F, 13.6F, 18.4F, 6F, 1.7F, 0.5F)
            .texOffs(86, 35)
            .addBox(-3.85F, 5.6F, 3.2F, 0.9F, 1.6F, 6.8F)
            .texOffs(21, 46)
            .addBox(-3.62F, 5.9F, 3.4F, 0.45F, 1F, 6.4F)
            .texOffs(110, 55)
            .addBox(2.6F, 6.2F, 0.6F, 1.8F, 1.6F, 3.4F)
            .texOffs(67, 35)
            .addBox(3.3F, 6.6F, 3.9F, 1.5F, 1.4F, 7.3F)
            .texOffs(27, 23)
            .addBox(3.4F, 6F, 11.2F, 2.6F, 3.6F, 6.6F)
            .texOffs(47, 62)
            .addBox(3.3F, 5.9F, 13.9F, 2.8F, 3.8F, 0.7F)
            .texOffs(0, 46)
            .addBox(-3.5F, 11.5F, -8.4F, 7F, 4.2F, 3F)
            .texOffs(95, 55)
            .addBox(-3F, 11F, -9.3F, 6F, 3.2F, 1F)
            .texOffs(86, 62)
            .addBox(-2.6F, 15.6F, -8F, 5.2F, 0.9F, 2.7F)
            .texOffs(55, 62)
            .addBox(-4.3F, 11.2F, -8F, 0.8F, 2.6F, 2.2F)
            .texOffs(62, 62)
            .addBox(3.5F, 11.2F, -8F, 0.8F, 2.6F, 2.2F)
            .texOffs(122, 73)
            .addBox(-4.5F, 11.7F, -8.2F, 1.1F, 0.9F, 1.4F)
            .texOffs(0, 78)
            .addBox(3.4F, 11.7F, -8.2F, 1.1F, 0.9F, 1.4F)
            .texOffs(62, 68)
            .addBox(-2.3F, 11F, -10.2F, 4.6F, 2.5F, 0.9F)
            , PartPose.ZERO);
            PartDefinition windscreen = body.addOrReplaceChild("windscreen", CubeListBuilder.create()
                .texOffs(49, 68)
                .addBox(-2.5F, 0F, -0.35F, 5F, 2.9F, 0.7F)
                , PartPose.offsetAndRotation(0F, 15.4F, -6.9F, 0.3142F, 0F, 0F));
            PartDefinition side_stand = body.addOrReplaceChild("side_stand", CubeListBuilder.create()
                .texOffs(69, 62)
                .addBox(-0.35F, -4.3F, -0.35F, 0.7F, 4.3F, 0.7F)
                .texOffs(69, 62)
                .addBox(-0.9F, -4.7F, -0.5F, 1.8F, 0.45F, 1F)
                , PartPose.offset(-2.7F, 5F, 2.6F));
        PartDefinition steering = root.addOrReplaceChild("steering", CubeListBuilder.create()
            .texOffs(115, 73)
            .addBox(-0.9F, -0.3F, -0.5F, 1.8F, 1.6F, 1.2F)
            .texOffs(4, 73)
            .addBox(-2.7F, 0.8F, -0.9F, 5.4F, 0.9F, 1.7F)
            , PartPose.offset(0F, 13.5F, -4.6F));
            PartDefinition handlebar = steering.addOrReplaceChild("handlebar", CubeListBuilder.create()
                .texOffs(12, 78)
                .addBox(-6.4F, 0.7F, -0.45F, 12.8F, 0.85F, 0.95F)
                .texOffs(106, 78)
                .addBox(-0.9F, -0.2F, -0.45F, 1.8F, 1F, 0.95F)
                .texOffs(76, 78)
                .addBox(-6.7F, 0.65F, -0.5F, 2.3F, 0.95F, 1.05F)
                .texOffs(84, 78)
                .addBox(4.4F, 0.65F, -0.5F, 2.3F, 0.95F, 1.05F)
                .texOffs(92, 78)
                .addBox(-4.6F, 1.35F, -1.2F, 1.7F, 0.42F, 0.85F)
                .texOffs(99, 78)
                .addBox(2.9F, 1.35F, -1.2F, 1.7F, 0.42F, 0.85F)
                .texOffs(6, 78)
                .addBox(-4.7F, 1.5F, -0.25F, 0.5F, 2.5F, 0.5F)
                .texOffs(9, 78)
                .addBox(4.2F, 1.5F, -0.25F, 0.5F, 2.5F, 0.5F)
                .texOffs(99, 73)
                .addBox(-6.7F, 3.8F, -0.9F, 2.7F, 1.9F, 0.5F)
                .texOffs(107, 73)
                .addBox(4F, 3.8F, -0.9F, 2.7F, 1.9F, 0.5F)
                .texOffs(49, 73)
                .addBox(-1.9F, 1.2F, -1.2F, 3.8F, 1.4F, 1.6F)
                , PartPose.offset(0F, 1.4F, -0.2F));
            PartDefinition fork = steering.addOrReplaceChild("fork", CubeListBuilder.create()
                .texOffs(46, 46)
                .addBox(-2.4F, -6.2F, -0.55F, 0.95F, 6.8F, 1.1F)
                .texOffs(52, 46)
                .addBox(1.45F, -6.2F, -0.55F, 0.95F, 6.8F, 1.1F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 0.4504F, 0F, 0F));
                PartDefinition fork_lower = fork.addOrReplaceChild("fork_lower", CubeListBuilder.create()
                    .texOffs(43, 55)
                    .addBox(-2.45F, -4.4F, -0.65F, 1.05F, 4.7F, 1.3F)
                    .texOffs(49, 55)
                    .addBox(1.4F, -4.4F, -0.65F, 1.05F, 4.7F, 1.3F)
                    , PartPose.offset(0F, -6.2F, 0F));
                    PartDefinition front_wheel = fork_lower.addOrReplaceChild("front_wheel", CubeListBuilder.create()
                        , PartPose.offset(0F, -3.9F, 0F));
                        PartDefinition front_tire0 = front_wheel.addOrReplaceChild("front_tire0", CubeListBuilder.create()
                            .texOffs(0, 62)
                            .addBox(-1.05F, -4.42F, -1.4728F, 2.1F, 1.12F, 2.9456F)
                            , PartPose.ZERO);
                        PartDefinition front_tire1 = front_wheel.addOrReplaceChild("front_tire1", CubeListBuilder.create()
                            .texOffs(0, 62)
                            .addBox(-1.05F, -4.42F, -1.4728F, 2.1F, 1.12F, 2.9456F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 0.6283F, 0F, 0F));
                        PartDefinition front_tire2 = front_wheel.addOrReplaceChild("front_tire2", CubeListBuilder.create()
                            .texOffs(0, 62)
                            .addBox(-1.05F, -4.42F, -1.4728F, 2.1F, 1.12F, 2.9456F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 1.2566F, 0F, 0F));
                        PartDefinition front_tire3 = front_wheel.addOrReplaceChild("front_tire3", CubeListBuilder.create()
                            .texOffs(0, 62)
                            .addBox(-1.05F, -4.42F, -1.4728F, 2.1F, 1.12F, 2.9456F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 1.885F, 0F, 0F));
                        PartDefinition front_tire4 = front_wheel.addOrReplaceChild("front_tire4", CubeListBuilder.create()
                            .texOffs(0, 62)
                            .addBox(-1.05F, -4.42F, -1.4728F, 2.1F, 1.12F, 2.9456F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 2.5133F, 0F, 0F));
                        PartDefinition front_tire5 = front_wheel.addOrReplaceChild("front_tire5", CubeListBuilder.create()
                            .texOffs(0, 62)
                            .addBox(-1.05F, -4.42F, -1.4728F, 2.1F, 1.12F, 2.9456F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 3.1416F, 0F, 0F));
                        PartDefinition front_tire6 = front_wheel.addOrReplaceChild("front_tire6", CubeListBuilder.create()
                            .texOffs(0, 62)
                            .addBox(-1.05F, -4.42F, -1.4728F, 2.1F, 1.12F, 2.9456F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 3.7699F, 0F, 0F));
                        PartDefinition front_tire7 = front_wheel.addOrReplaceChild("front_tire7", CubeListBuilder.create()
                            .texOffs(0, 62)
                            .addBox(-1.05F, -4.42F, -1.4728F, 2.1F, 1.12F, 2.9456F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 4.3982F, 0F, 0F));
                        PartDefinition front_tire8 = front_wheel.addOrReplaceChild("front_tire8", CubeListBuilder.create()
                            .texOffs(0, 62)
                            .addBox(-1.05F, -4.42F, -1.4728F, 2.1F, 1.12F, 2.9456F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 5.0265F, 0F, 0F));
                        PartDefinition front_tire9 = front_wheel.addOrReplaceChild("front_tire9", CubeListBuilder.create()
                            .texOffs(0, 62)
                            .addBox(-1.05F, -4.42F, -1.4728F, 2.1F, 1.12F, 2.9456F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 5.6549F, 0F, 0F));
                        PartDefinition front_rim0 = front_wheel.addOrReplaceChild("front_rim0", CubeListBuilder.create()
                            .texOffs(97, 68)
                            .addBox(-0.882F, -3.86F, -1.5853F, 1.764F, 0.48F, 3.1706F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 0.3927F, 0F, 0F));
                        PartDefinition front_rim1 = front_wheel.addOrReplaceChild("front_rim1", CubeListBuilder.create()
                            .texOffs(97, 68)
                            .addBox(-0.882F, -3.86F, -1.5853F, 1.764F, 0.48F, 3.1706F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 1.1781F, 0F, 0F));
                        PartDefinition front_rim2 = front_wheel.addOrReplaceChild("front_rim2", CubeListBuilder.create()
                            .texOffs(97, 68)
                            .addBox(-0.882F, -3.86F, -1.5853F, 1.764F, 0.48F, 3.1706F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 1.9635F, 0F, 0F));
                        PartDefinition front_rim3 = front_wheel.addOrReplaceChild("front_rim3", CubeListBuilder.create()
                            .texOffs(97, 68)
                            .addBox(-0.882F, -3.86F, -1.5853F, 1.764F, 0.48F, 3.1706F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 2.7489F, 0F, 0F));
                        PartDefinition front_rim4 = front_wheel.addOrReplaceChild("front_rim4", CubeListBuilder.create()
                            .texOffs(97, 68)
                            .addBox(-0.882F, -3.86F, -1.5853F, 1.764F, 0.48F, 3.1706F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 3.5343F, 0F, 0F));
                        PartDefinition front_rim5 = front_wheel.addOrReplaceChild("front_rim5", CubeListBuilder.create()
                            .texOffs(97, 68)
                            .addBox(-0.882F, -3.86F, -1.5853F, 1.764F, 0.48F, 3.1706F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 4.3197F, 0F, 0F));
                        PartDefinition front_rim6 = front_wheel.addOrReplaceChild("front_rim6", CubeListBuilder.create()
                            .texOffs(97, 68)
                            .addBox(-0.882F, -3.86F, -1.5853F, 1.764F, 0.48F, 3.1706F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 5.1051F, 0F, 0F));
                        PartDefinition front_rim7 = front_wheel.addOrReplaceChild("front_rim7", CubeListBuilder.create()
                            .texOffs(97, 68)
                            .addBox(-0.882F, -3.86F, -1.5853F, 1.764F, 0.48F, 3.1706F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 5.8905F, 0F, 0F));
                        PartDefinition front_spoke0 = front_wheel.addOrReplaceChild("front_spoke0", CubeListBuilder.create()
                            .texOffs(124, 68)
                            .addBox(-0.3F, -3.62F, -0.3F, 0.6F, 2.62F, 0.6F)
                            , PartPose.ZERO);
                        PartDefinition front_spoke1 = front_wheel.addOrReplaceChild("front_spoke1", CubeListBuilder.create()
                            .texOffs(124, 68)
                            .addBox(-0.3F, -3.62F, -0.3F, 0.6F, 2.62F, 0.6F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 0.7854F, 0F, 0F));
                        PartDefinition front_spoke2 = front_wheel.addOrReplaceChild("front_spoke2", CubeListBuilder.create()
                            .texOffs(124, 68)
                            .addBox(-0.3F, -3.62F, -0.3F, 0.6F, 2.62F, 0.6F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 1.5708F, 0F, 0F));
                        PartDefinition front_spoke3 = front_wheel.addOrReplaceChild("front_spoke3", CubeListBuilder.create()
                            .texOffs(124, 68)
                            .addBox(-0.3F, -3.62F, -0.3F, 0.6F, 2.62F, 0.6F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 2.3562F, 0F, 0F));
                        PartDefinition front_spoke4 = front_wheel.addOrReplaceChild("front_spoke4", CubeListBuilder.create()
                            .texOffs(124, 68)
                            .addBox(-0.3F, -3.62F, -0.3F, 0.6F, 2.62F, 0.6F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 3.1416F, 0F, 0F));
                        PartDefinition front_spoke5 = front_wheel.addOrReplaceChild("front_spoke5", CubeListBuilder.create()
                            .texOffs(124, 68)
                            .addBox(-0.3F, -3.62F, -0.3F, 0.6F, 2.62F, 0.6F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 3.927F, 0F, 0F));
                        PartDefinition front_spoke6 = front_wheel.addOrReplaceChild("front_spoke6", CubeListBuilder.create()
                            .texOffs(124, 68)
                            .addBox(-0.3F, -3.62F, -0.3F, 0.6F, 2.62F, 0.6F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 4.7124F, 0F, 0F));
                        PartDefinition front_spoke7 = front_wheel.addOrReplaceChild("front_spoke7", CubeListBuilder.create()
                            .texOffs(124, 68)
                            .addBox(-0.3F, -3.62F, -0.3F, 0.6F, 2.62F, 0.6F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 5.4978F, 0F, 0F));
                        PartDefinition front_hub = front_wheel.addOrReplaceChild("front_hub", CubeListBuilder.create()
                            .texOffs(36, 62)
                            .addBox(-1.15F, -1.25F, -1.25F, 2.3F, 2.5F, 2.5F)
                            , PartPose.ZERO);
                        PartDefinition front_drum_r = front_wheel.addOrReplaceChild("front_drum_r", CubeListBuilder.create()
                            .texOffs(103, 46)
                            .addBox(1.05F, -1.7F, -1.7F, 0.75F, 3.4F, 3.4F)
                            , PartPose.ZERO);
                    PartDefinition front_fender = fork_lower.addOrReplaceChild("front_fender", CubeListBuilder.create()
                        , PartPose.offset(0F, -3.9F, 0F));
                        PartDefinition fender_seg0 = front_fender.addOrReplaceChild("fender_seg0", CubeListBuilder.create()
                            .texOffs(34, 68)
                            .addBox(-1.9F, -5.75F, -1.45F, 3.8F, 0.7F, 2.9F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 1.1868F, 0F, 0F));
                        PartDefinition fender_seg1 = front_fender.addOrReplaceChild("fender_seg1", CubeListBuilder.create()
                            .texOffs(34, 68)
                            .addBox(-1.9F, -5.75F, -1.45F, 3.8F, 0.7F, 2.9F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 1.6755F, 0F, 0F));
                        PartDefinition fender_seg2 = front_fender.addOrReplaceChild("fender_seg2", CubeListBuilder.create()
                            .texOffs(34, 68)
                            .addBox(-1.9F, -5.75F, -1.45F, 3.8F, 0.7F, 2.9F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 2.1642F, 0F, 0F));
                        PartDefinition fender_seg3 = front_fender.addOrReplaceChild("fender_seg3", CubeListBuilder.create()
                            .texOffs(34, 68)
                            .addBox(-1.9F, -5.75F, -1.45F, 3.8F, 0.7F, 2.9F)
                            , PartPose.offsetAndRotation(0F, 0F, 0F, 2.6529F, 0F, 0F));
        PartDefinition rear_wheel = root.addOrReplaceChild("rear_wheel", CubeListBuilder.create()
            , PartPose.offset(0F, 4.4F, 10F));
            PartDefinition rear_tire0 = rear_wheel.addOrReplaceChild("rear_tire0", CubeListBuilder.create()
                .texOffs(24, 62)
                .addBox(-1.25F, -4.42F, -1.4728F, 2.5F, 1.12F, 2.9456F)
                , PartPose.ZERO);
            PartDefinition rear_tire1 = rear_wheel.addOrReplaceChild("rear_tire1", CubeListBuilder.create()
                .texOffs(24, 62)
                .addBox(-1.25F, -4.42F, -1.4728F, 2.5F, 1.12F, 2.9456F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 0.6283F, 0F, 0F));
            PartDefinition rear_tire2 = rear_wheel.addOrReplaceChild("rear_tire2", CubeListBuilder.create()
                .texOffs(24, 62)
                .addBox(-1.25F, -4.42F, -1.4728F, 2.5F, 1.12F, 2.9456F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 1.2566F, 0F, 0F));
            PartDefinition rear_tire3 = rear_wheel.addOrReplaceChild("rear_tire3", CubeListBuilder.create()
                .texOffs(24, 62)
                .addBox(-1.25F, -4.42F, -1.4728F, 2.5F, 1.12F, 2.9456F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 1.885F, 0F, 0F));
            PartDefinition rear_tire4 = rear_wheel.addOrReplaceChild("rear_tire4", CubeListBuilder.create()
                .texOffs(24, 62)
                .addBox(-1.25F, -4.42F, -1.4728F, 2.5F, 1.12F, 2.9456F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 2.5133F, 0F, 0F));
            PartDefinition rear_tire5 = rear_wheel.addOrReplaceChild("rear_tire5", CubeListBuilder.create()
                .texOffs(24, 62)
                .addBox(-1.25F, -4.42F, -1.4728F, 2.5F, 1.12F, 2.9456F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 3.1416F, 0F, 0F));
            PartDefinition rear_tire6 = rear_wheel.addOrReplaceChild("rear_tire6", CubeListBuilder.create()
                .texOffs(24, 62)
                .addBox(-1.25F, -4.42F, -1.4728F, 2.5F, 1.12F, 2.9456F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 3.7699F, 0F, 0F));
            PartDefinition rear_tire7 = rear_wheel.addOrReplaceChild("rear_tire7", CubeListBuilder.create()
                .texOffs(24, 62)
                .addBox(-1.25F, -4.42F, -1.4728F, 2.5F, 1.12F, 2.9456F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 4.3982F, 0F, 0F));
            PartDefinition rear_tire8 = rear_wheel.addOrReplaceChild("rear_tire8", CubeListBuilder.create()
                .texOffs(24, 62)
                .addBox(-1.25F, -4.42F, -1.4728F, 2.5F, 1.12F, 2.9456F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 5.0265F, 0F, 0F));
            PartDefinition rear_tire9 = rear_wheel.addOrReplaceChild("rear_tire9", CubeListBuilder.create()
                .texOffs(24, 62)
                .addBox(-1.25F, -4.42F, -1.4728F, 2.5F, 1.12F, 2.9456F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 5.6549F, 0F, 0F));
            PartDefinition rear_rim0 = rear_wheel.addOrReplaceChild("rear_rim0", CubeListBuilder.create()
                .texOffs(74, 68)
                .addBox(-1.05F, -3.86F, -1.5853F, 2.1F, 0.48F, 3.1706F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 0.3927F, 0F, 0F));
            PartDefinition rear_rim1 = rear_wheel.addOrReplaceChild("rear_rim1", CubeListBuilder.create()
                .texOffs(74, 68)
                .addBox(-1.05F, -3.86F, -1.5853F, 2.1F, 0.48F, 3.1706F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 1.1781F, 0F, 0F));
            PartDefinition rear_rim2 = rear_wheel.addOrReplaceChild("rear_rim2", CubeListBuilder.create()
                .texOffs(74, 68)
                .addBox(-1.05F, -3.86F, -1.5853F, 2.1F, 0.48F, 3.1706F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 1.9635F, 0F, 0F));
            PartDefinition rear_rim3 = rear_wheel.addOrReplaceChild("rear_rim3", CubeListBuilder.create()
                .texOffs(74, 68)
                .addBox(-1.05F, -3.86F, -1.5853F, 2.1F, 0.48F, 3.1706F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 2.7489F, 0F, 0F));
            PartDefinition rear_rim4 = rear_wheel.addOrReplaceChild("rear_rim4", CubeListBuilder.create()
                .texOffs(74, 68)
                .addBox(-1.05F, -3.86F, -1.5853F, 2.1F, 0.48F, 3.1706F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 3.5343F, 0F, 0F));
            PartDefinition rear_rim5 = rear_wheel.addOrReplaceChild("rear_rim5", CubeListBuilder.create()
                .texOffs(74, 68)
                .addBox(-1.05F, -3.86F, -1.5853F, 2.1F, 0.48F, 3.1706F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 4.3197F, 0F, 0F));
            PartDefinition rear_rim6 = rear_wheel.addOrReplaceChild("rear_rim6", CubeListBuilder.create()
                .texOffs(74, 68)
                .addBox(-1.05F, -3.86F, -1.5853F, 2.1F, 0.48F, 3.1706F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 5.1051F, 0F, 0F));
            PartDefinition rear_rim7 = rear_wheel.addOrReplaceChild("rear_rim7", CubeListBuilder.create()
                .texOffs(74, 68)
                .addBox(-1.05F, -3.86F, -1.5853F, 2.1F, 0.48F, 3.1706F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 5.8905F, 0F, 0F));
            PartDefinition rear_spoke0 = rear_wheel.addOrReplaceChild("rear_spoke0", CubeListBuilder.create()
                .texOffs(0, 73)
                .addBox(-0.3F, -3.62F, -0.3F, 0.6F, 2.62F, 0.6F)
                , PartPose.ZERO);
            PartDefinition rear_spoke1 = rear_wheel.addOrReplaceChild("rear_spoke1", CubeListBuilder.create()
                .texOffs(0, 73)
                .addBox(-0.3F, -3.62F, -0.3F, 0.6F, 2.62F, 0.6F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 0.7854F, 0F, 0F));
            PartDefinition rear_spoke2 = rear_wheel.addOrReplaceChild("rear_spoke2", CubeListBuilder.create()
                .texOffs(0, 73)
                .addBox(-0.3F, -3.62F, -0.3F, 0.6F, 2.62F, 0.6F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 1.5708F, 0F, 0F));
            PartDefinition rear_spoke3 = rear_wheel.addOrReplaceChild("rear_spoke3", CubeListBuilder.create()
                .texOffs(0, 73)
                .addBox(-0.3F, -3.62F, -0.3F, 0.6F, 2.62F, 0.6F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 2.3562F, 0F, 0F));
            PartDefinition rear_spoke4 = rear_wheel.addOrReplaceChild("rear_spoke4", CubeListBuilder.create()
                .texOffs(0, 73)
                .addBox(-0.3F, -3.62F, -0.3F, 0.6F, 2.62F, 0.6F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 3.1416F, 0F, 0F));
            PartDefinition rear_spoke5 = rear_wheel.addOrReplaceChild("rear_spoke5", CubeListBuilder.create()
                .texOffs(0, 73)
                .addBox(-0.3F, -3.62F, -0.3F, 0.6F, 2.62F, 0.6F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 3.927F, 0F, 0F));
            PartDefinition rear_spoke6 = rear_wheel.addOrReplaceChild("rear_spoke6", CubeListBuilder.create()
                .texOffs(0, 73)
                .addBox(-0.3F, -3.62F, -0.3F, 0.6F, 2.62F, 0.6F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 4.7124F, 0F, 0F));
            PartDefinition rear_spoke7 = rear_wheel.addOrReplaceChild("rear_spoke7", CubeListBuilder.create()
                .texOffs(0, 73)
                .addBox(-0.3F, -3.62F, -0.3F, 0.6F, 2.62F, 0.6F)
                , PartPose.offsetAndRotation(0F, 0F, 0F, 5.4978F, 0F, 0F));
            PartDefinition rear_hub = rear_wheel.addOrReplaceChild("rear_hub", CubeListBuilder.create()
                .texOffs(12, 62)
                .addBox(-1.35F, -1.25F, -1.25F, 2.7F, 2.5F, 2.5F)
                , PartPose.ZERO);
            PartDefinition rear_drum_l = rear_wheel.addOrReplaceChild("rear_drum_l", CubeListBuilder.create()
                .texOffs(36, 46)
                .addBox(-2F, -1.7F, -1.7F, 0.75F, 3.4F, 3.4F)
                , PartPose.ZERO);
            PartDefinition rear_sprocket = rear_wheel.addOrReplaceChild("rear_sprocket", CubeListBuilder.create()
                .texOffs(36, 46)
                .addBox(-2.4F, -1.8F, -1.8F, 0.55F, 3.6F, 3.6F)
                , PartPose.ZERO);
        PartDefinition headlight_lens = root.addOrReplaceChild("headlight_lens", CubeListBuilder.create()
            .texOffs(72, 73)
            .addBox(-2.05F, 11.25F, -10.75F, 4.1F, 2.05F, 0.5F)
            , PartPose.ZERO);
        PartDefinition tail_lens = root.addOrReplaceChild("tail_lens", CubeListBuilder.create()
            .texOffs(66, 78)
            .addBox(-1.85F, 11.3F, 18.65F, 3.7F, 0.95F, 0.4F)
            , PartPose.ZERO);
        PartDefinition beam_inner = root.addOrReplaceChild("beam_inner", CubeListBuilder.create()
            .texOffs(0, 0)
            .addBox(-1.1F, 11.7F, -30.6F, 2.2F, 1.3F, 19.8F)
            , PartPose.ZERO);
        PartDefinition beam_outer = root.addOrReplaceChild("beam_outer", CubeListBuilder.create()
            .texOffs(45, 0)
            .addBox(-2.1F, 11.15F, -26.6F, 4.2F, 2.4F, 15.8F)
            , PartPose.ZERO);
        return LayerDefinition.create(mesh, 128, 128);
    }

    @Override
    public ModelPart root() {
        return this.root;
    }

    @Override
    public void setupAnim(Entity entity, float limbSwing, float limbSwingAmount,
                          float ageInTicks, float netHeadYaw, float headPitch) {
    }
}
